#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

#
include $(CCSP_ROOT_DIR)/arch/ccsp_common.mk

#
#	set up source and object targets
#
source_files := $(call add_files_from_src,,'*.c')
source_files += $(call add_files_from_arch,,'*.c')
source_files += $(call add_files_from_board,,'*.c')

obj_files := $(addprefix $(ComponentBuildDir)/, $(source_files:%.c=%.o))

#
#	set up include paths
#
CFLAGS += $(addprefix -I, $(INCPATH))

target := $(ComponentBuildDir)/CcspCrSsp

#
#	set up targets
#
all: $(target)

$(target): $(obj_files)

.PHONY: all clean

clean:
	rm -rf $(ComponentBuildDir)

install_targets := $(target)
# config directories from both arch and arch/board
install_targets += $(wildcard $(ComponentArchCfgDir)/*)
install_targets += $(wildcard $(ComponentBoardCfgDir)/*)

install:
	@echo "Installing CR Installables"
	@install -d -m 0755 $(CCSP_OUT_DIR)
	@cp $(install_targets) $(CCSP_OUT_DIR)
    
LDFLAGS   += -lccsp_common

#
# include custom post makefile, if exists
#
ifneq ($(findstring $(CCSP_CMPNT_BUILD_CUSTOM_MK_POST), $(wildcard $(ComponentBoardDir)/*.mk)), )
    include $(ComponentBoardDir)/$(CCSP_CMPNT_BUILD_CUSTOM_MK_POST)
endif
